/*=auto=========================================================================

  Portions (c) Copyright 2005 Brigham and Women's Hospital (BWH) All Rights Reserved.

  See Doc/copyright/copyright.txt
  or http://www.slicer.org/copyright/copyright.txt for details.

  Program:   3D Slicer
  Module:    $RCSfile: vtkStereoOptimizerGUI.h,v $
  Date:      $Date: 2006/03/19 17:12:29 $
  Version:   $Revision: 1.3 $

=========================================================================auto=*/
#ifndef __vtkStereoOptimizerGUI_h
#define __vtkStereoOptimizerGUI_h

#include <string>
#include <iostream>
#include <sstream>

#include "vtkSlicerBaseGUIWin32Header.h"
#include "vtkSlicerModuleGUI.h"

#include "vtkMRMLScene.h"
#include "vtkStereoOptimizerLogic.h"


//class vtkSlicerSliceWidget;
//class vtkKWFrame;
class vtkKWScaleWithEntry;
class vtkKWPushButton;
class vtkKWThumbWheel;
class vtkKWNotebook;
class vtkKWRenderWidget;
//class vtkSlicerNodeSelectorWidget;
//class vtkKWMultiColumnList;
//class vtkKWLoadSaveButton;

class VTK_STEREOOPTIMIZER_EXPORT vtkStereoOptimizerGUI : public vtkSlicerModuleGUI
{
  public:
  static vtkStereoOptimizerGUI *New();
  vtkTypeMacro(vtkStereoOptimizerGUI,vtkSlicerModuleGUI);
  void PrintSelf(ostream& os, vtkIndent indent);

   // Description: Get/Set MRML node
  vtkGetObjectMacro (Logic, vtkStereoOptimizerLogic);
  vtkSetObjectMacro (Logic, vtkStereoOptimizerLogic);
  
  // Description: Get/Set MRML node
   vtkGetObjectMacro (StereoOptimizerNode, vtkMRMLStereoOptimizerNode);

  // Description:
  // Create widgets
  virtual void BuildGUI ( );

  // Description:
  // Add obsereves to GUI widgets
  virtual void AddGUIObservers ( );
  
  // Description:
  // Remove obsereves to GUI widgets
  virtual void RemoveGUIObservers ( );
  
  // Description:
  // Process events generated by Logic
  virtual void ProcessLogicEvents ( vtkObject *caller, unsigned long event,
                                    void *callData );

  // Description:
  // Process events generated by GUI widgets
  virtual void ProcessGUIEvents ( vtkObject *caller, unsigned long event,
                                  void *callData );

  // Description:
  // Pprocess events generated by MRML
  virtual void ProcessMRMLEvents ( vtkObject *caller, unsigned long event, 
                                  void *callData);
  // Description:
  // Describe behavior at module startup and exit.
  virtual void Enter ( ){};
  virtual void Exit ( ){};
  
protected:
  vtkStereoOptimizerGUI();
  virtual ~vtkStereoOptimizerGUI();
  vtkStereoOptimizerGUI(const vtkStereoOptimizerGUI&);
  void operator=(const vtkStereoOptimizerGUI&);

  // Description:
  // Updates GUI widgets based on parameters values in MRML node
  void UpdateGUI();

  // Description:
  // Updates parameters values in MRML node based on GUI widgets 
  void UpdateMRML();
  
  int SideViewsRenderPending;
  vtkKWScaleWithEntry* ViewAngleScale;
  vtkKWScaleWithEntry* EyeAngleScale;
  vtkKWScaleWithEntry* PlaneOfProjectionScale;
   
  vtkKWScaleWithEntry* MaxParallaxScale;
  vtkKWScaleWithEntry* UserEyeDistanceScale;

  vtkStereoOptimizerLogic *Logic;
  vtkMRMLStereoOptimizerNode* StereoOptimizerNode;
  //vtkKWLoadSaveButton* SaveToFile;
  vtkKWPushButton* PushBehindScreenButton;
  vtkKWPushButton* OptimizeDepthButton;
  vtkKWPushButton* ResetButton;
  vtkKWThumbWheel* ViewDistanceWheel;
  vtkKWThumbWheel* ScreenWidthWheel;

  vtkKWRenderWidget *SideViewWidget;
  vtkKWRenderWidget *BirdsViewWidget;

};

#endif

